services:
  database:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=indexes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - my-network

  roman_api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: roman_converter
    depends_on: 
      - database
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    # networks:
    #   - my-network  
    ports:
    - "8080:8080" 

# networks:
#   my-network:  

volumes:
  pgdata:
